<a href="https://colab.research.google.com/github/merinrose4007/DSA-class-activity/blob/main/Basics_Merin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Exploring Python Notebook***
Here we are exploring some basics operations using google colab

In [ ]:
print('Hello World') #printing the phrase 'Hello World'

Hello World


In [ ]:
=

#topic2

##subtopic2

In [ ]:
age=23+1j

In [ ]:
print(age)

(23+1j)


In [ ]:
type(age)

complex

In [ ]:
name='Das'

In [ ]:
type(name)

str

In [ ]:
days=['th', 'mon', 'tue']

In [ ]:
type(days)

list

In [ ]:
days[0]

'th'

In [ ]:
list(range(8,-1,-2))

[8, 6, 4, 2, 0]

In [ ]:
details={'batch':7, 'course':'DSA'}

In [ ]:
details['batch']

7

In [ ]:
details.values()

dict_values([7, 'DSA'])

In [ ]:
details.keys()

dict_keys(['batch', 'course'])

In [ ]:
details['location']='TVM'

In [ ]:
print(details)

{'batch': 7, 'course': 'DSA', 'location': 'TVM'}


In [ ]:
set={'merin','Maria','Jiji'}

In [ ]:
type(set)

set

In [ ]:
10>30

False

In [ ]:
9//2

4

In [ ]:
year_of_birth=1998
year_now=2025
age=year_now-year_of_birth
print(age)

27


In [ ]:
bio_data={'age':23,\
          'name':'Merin','location':'Kozhikode'}

In [ ]:
print(bio_data)

{'age': 23, 'name': 'Merin', 'location': 'Kozhikode'}


In [ ]:
to_do_list=['To Make ppt for my project','to study for viva','to wash cloths']

In [ ]:
print(to_do_list[-2])

to study for viva


In [ ]:
print(to_do_list)

['To Make ppt for my project', 'to study for viva', 'to wash cloths']


In [ ]:
list(range(99,0,-2))

[99,
 97,
 95,
 93,
 91,
 89,
 87,
 85,
 83,
 81,
 79,
 77,
 75,
 73,
 71,
 69,
 67,
 65,
 63,
 61,
 59,
 57,
 55,
 53,
 51,
 49,
 47,
 45,
 43,
 41,
 39,
 37,
 35,
 33,
 31,
 29,
 27,
 25,
 23,
 21,
 19,
 17,
 15,
 13,
 11,
 9,
 7,
 5,
 3,
 1]

In [ ]:
m='Merin'
print(len(m))

5


In [ ]:
x=input("Enter:")
print(x)
type(x)

Enter:2
2


str

In [ ]:
num1=input("Enter a number")
num2=input("Enter a number")
sum=int(num1)+int(num2)
mul=int(num1)*int(num2)
sub=int(num1)-int(num2)
div=int(num1)/int(num2)
print(sum,mul,div,sub)



Enter a number15
Enter a number3
18 45 5.0 12


In [ ]:
x=int(input("Enter your age:"))
print('My age is',x)
print(f"You are {x} years old")

Enter your age:23
My age is 23
You are 23 years old


In [ ]:
year=int(input("Enter your year of birth"))
age=2025-year
print(f"i am {age} years old and i was born on {year}")

Enter your year of birth2001
i am 24 years old and i was born on 2001


In [ ]:
num=9
den=2
result=num//den
c=num**den

print(c)
print(result)

81
4


In [ ]:
print(True and True)

True


In [ ]:
print(True or False)

True


In [ ]:
print(not False)

True


In [ ]:
print(False and True)

False


In [ ]:
print(1 in[1,2,3])
print(1 not in [2,3,4])
print('m' in 'MalayalaM')

True
True
False


In [ ]:
"hello"*2

'hellohello'

In [ ]:
"mer"+"in"

'merin'

In [ ]:
msg=input("Enter the msg:")
num=int(input("Enter the number of time:"))

Enter the msg:jdnjcsjnscj
Enter the number of time:4
jdnjcsjnscjjdnjcsjnscjjdnjcsjnscjjdnjcsjnscj 



In [ ]:
print("hello all good evening\n "*5)

hello all good evening
 hello all good evening
 hello all good evening
 hello all good evening
 hello all good evening
 


In [ ]:
'ICT academy of kerala'[4:11]

'academy'

In [ ]:
a=input("Enter the name:")
a==a[::-1]

Enter the name:malayalam


True

In [ ]:
ar=input('Enter the 4-digit OTP number:').split(" ")
p=ar[0]
q=ar[1]
r=ar[2]
s=ar[3]
dic={'zero':'0',
'one':'1',
'two':'2',
'three':'3',
'four':'4',
'five':'5',
'six':'6',
'7':'seven',
'8':'eight',
'9':'nine'}
print(dic[p],dic[q],dic[r],dic[s])

Enter the 4-digit OTP number:one two three four
1 2 3 4


In [ ]:
digit=['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']


In [ ]:
year=int(input("Enter your birth year:"))
age=2025-year
if age>=18:
  print("Eligible to vote")
else:
  print("Not Eligible to vote")

Enter the date of year:2001
Eligible to vote


In [ ]:
age=int(input("Enter the age:"))
if age<=12:
  print("Child")
  if age<10:
    print("Teenage")
elif 20<=age<=59:
  print("Adult")
else:
  print("Senior Citizen")

Enter the age:66
Senior Citizen


In [ ]:
x=input("Enter the name")
y=len(x)
if y>10:
  print("Name is lengthy")
else:
  print("Name is not lengthy")

Enter the nameMerin
name is not lenghty


In [ ]:
x=input("Enter the railway time:")
z=x.split(":")
y=int(z[0])
if y<=12:
  print(x,"AM")
elif y>12:
  print(y-12,":",z[1],"PM")


Enter the railway time:18:31
6 : 31 PM


In [ ]:
x=input("Enter the word")
y=x[::-1]
if x==y:
  print("patlindrome")
else:
  print("not palindrome")

Enter the wordmalayalam
patlindrome


In [ ]:
y=["red", "blue", "green", "Red", "Green","Blue", "RED", "BLUE", 'GREEN']
clr=input("Enter your fav color:")
if clr in y:
  print("Fav clr is a primary clr")
else:
  print("Not in primary clrs")



Enter your fav color:red
Fav clr is a primary clr


In [ ]:
MFD=input("Enter the MFD").split("/")
todays_date=input("Enter the date").split("/")
da=int(todays_date[0])
du=int(todays_date[1])
de=int(todays_date[2])
x=int(MFD[0])
y=int(MFD[1])
z=int(MFD[2])
if y<=6:
  print(x,"/",y+6,"/",z)
else:
  y=y+6
  y=y-12
  print(x,"/",y,"/",z+1)
if da==x+1 & du<=y & de<=z:
  print("Expired")
else:
  print("Not")


Enter the MFD03/02/2025
Enter the date04/05/2025
3 / 8 / 2025
Not


In [ ]:
x=int(input("Enter the number"))
y=int(input("Enter the number"))
z=int(input("Enter the number"))
if x>=y:
  if x>=z:
    a=x
  elif z>=y:
    a=z
  print(a,"is the greatest")
else:
  if y>=z:
    b=y
  elif y<=z:
    b=z
  print(b,"is the greatest")



Enter the number5
Enter the number3
Enter the number4
5 is the greatest


In [ ]:
l=["monday", "tuesday", "wednesday", "thursday", "friday"]
f=["saturday", "sunday"]
day=input("enter the day:")
if day in l:
  print("Is not a holiday")
else:
  print(day,"is a holiday")

enter the day:saturday
saturday is a holiday


In [ ]:
a=2
b=3.14159
print("a contain {}". format(a,))
print("a contain {} b contain{}". format(a,b))
print("b contain {1} contain {0}". format(a,b))
print(f"a contain {a} b contain {b}")
print(f"b contain {b:.3f}")

a contain 2
a contain 2 b contain3.14159
b contain 3.14159 contain 2
a contain 2 b contain 3.14159
b contain 3.142


In [ ]:
name, age, location="Guest", 23, "Kozhikode"
print(name)
print(age)
print(location)

Guest
23
Kozhikode


In [ ]:
q=5
b=str(q)
print(b, type(b))

5 <class 'str'>


In [ ]:
a="1"
b=int(a)
print(type(b))

<class 'int'>


In [ ]:
l=["merin","maria","jiji","smitha"]
k=tuple(l)
print(k)

('merin', 'maria', 'jiji', 'smitha')


In [ ]:
l=("merin","maria","jiji","smitha")
k=list(l)
print(k)

['merin', 'maria', 'jiji', 'smitha']


In [ ]:
list("abc")

['a', 'b', 'c']

In [ ]:
bool(0)

False

In [ ]:
set([1,2,3])

{1, 2, 3}

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
domain=["data", "science"]
"_".join(domain)

'data_science'

In [ ]:
x=[1,2,3]
x.append(4)
print(x)
x.extend([5,6])
print(x)
x.remove(2)
print(x)
x.insert(0,10)
print(x)


[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]
[1, 3, 4, 5, 6]
['a', 1, 3, 4, 5, 6]


In [ ]:
y=input("Enter the date").split("/")
print("-".join(y))
print(y[1],"-",y[0],"-",y[2])
print(y[2],"|",y[0],"-",y[1])

Enter the date11/11/2011
11-11-2011
11 - 11 - 2011
2011 - 11 - 11


for loop

In [ ]:




l={'tomato':10, 'carrot':40, 'banana':30, 'curd':20, 'milk':25, 'rice':50, 'wheat':15}
my_budget=150
my_list=[]
tot_price=0
for a,b in l.items():
  if b<my_budget and tot_price+b<=my_budget:
    my_list.append(a)
    tot_price=tot_price+b
print(my_list)

['tomato', 'carrot', 'banana', 'curd', 'milk', 'wheat']


In [ ]:
for i in range(1,101):
  if i%3==0 and i%5==0:
    print(i)

15
30
45
60
75
90


while

In [ ]:
A=1
while A<10:
  print(A)
  A=A+2
else:
  print("the limit has crossed")

1
3
5
7
9
the limit has crossed


In [ ]:
import random
a=int(input("Enter a number"))
b=random.randint(1, 100)
while a!=b:
  if a<b:
    print("Guess greater")
    a=int(input("Enter a number"))
  elif a>b:
    print("Guess lesser")
    a=int(input("Enter a number"))
else:
  print("your ans is correct")

Enter a number10
Guess greater
Enter a number20
Guess lesser
Enter a number11
Guess greater
Enter a number15
Guess lesser
Enter a number14
Guess lesser
Enter a number13
your ans is correct


In [ ]:
a=input("Enter the password:")
b="3142"
i=1
while a!=b:
    print("wrong password")
    print(3-i,"attempts are left")
    a=input("Enter the password:")
    i=i+1
    if i==3:
      print("Retry after 2hr")
      break
else:
  print("your ans is correct")

Enter the password:32312
wrong password
2 attemppts are left
Enter the password:3321
wrong password
1 attemppts are left
Enter the password:3142
Retry after 2hr


In [ ]:
dic={'movie A':3, 'movie B':8, 'movie C': 7, 'movie D': 6, 'movie E':9}
i=0

In [ ]:
for a,b in dic.items():
  print(a,b)
  if dic[a]==5:
    dic[a]=9
  elif dic[a]==8:
    dic[a]=5

print(dic)

movie A 3
movie B 8
movie C 7
movie D 6
movie E 9
{'movie A': 3, 'movie B': 5, 'movie C': 7, 'movie D': 6, 'movie E': 9}


In [ ]:
dic.update({'movie F': 5, 'movie G': 1})

In [ ]:
print(dic)

{'movie A': 3, 'movie B': 5, 'movie C': 7, 'movie D': 6, 'movie E': 9, 'movie F': 5, 'movie G': 1}


In [ ]:
g=dic['movie A']
for a,b in dic.items():
  if g<dic[a]:
    g=dic[a]
    h=a
print(h)


movie E


In [ ]:
for a,b in dic.items():
  if b<5:
    dic.pop(a)

In [ ]:
def greet(name, age):
  print("My namr is",name, "i am",age)
greet('Merin',23)
greet('Maria',19)

My namr is Merin i am 23
My namr is Maria i am 19


In [ ]:
def greet(name, age=19):#default value for age
  print("My namr is",name, "i am",age)
greet('Merin',23)
greet('Maria')

My namr is Merin i am 23
My namr is Maria i am 19


In [ ]:
def multiply(a,b):
  print(a,"*",b,"=",a*b)
num1=int(input("enter the value:"))
num2=int(input("enter the value:"))
multiply(num1,num2)

enter the value:2
enter the value:3
2 * 3 = 6


In [ ]:
def bill(total):
  if total<500:
    a=total*10/100
  elif 1000>total>=500:
    a=total*15/100
  elif total>=1000:
    a=total*20/100
  print("the total amount is",total+a)
t=int(input("Enter the amount:"))
bill(t)

Enter the amount:1000
the total amount is 1200.0


In [ ]:
from re import I
num_list=[12,4,5,7,8,13,10,21]

def average_even(numberlist):
  i=0
  s=0
  even_list=[]
  odd_list=[]
  for num in numberlist:
    if num%2==0:
      even_list.append(num)
      s=s+num
      i=i+1
    else:
       odd_list.append(num)
       r=r+num
       j=j+1
  print(even_list)
  print(odd_list)
  print(s/i)
  print(r/j)
average_even(num_list)


[12, 4, 8, 10]
[5, 7, 13, 21]
8.5
11.5


In [ ]:
def sum_numbers(*args):#* arbitary arguments
  print(type(args))
  total=0
  for i in args:
    total=total+i
  print(total)
sum_numbers(2,3,4)


<class 'tuple'>
9


In [ ]:
def numbers(**arg):#** keyword Arguement
  for a,b in arg.items():
    print(a,"is",b)
numbers(name="Merin", place="kozhikode")

name is Merin
place is kozhikode


In [ ]:
def squareofnum(x):
  y=x*x
  print(y)
squareofnum(3)

9


In [ ]:
square=lambda x:x*x
square(5)

25

In [ ]:
add = lambda x,y : x+y
add(3,5)

8

In [ ]:
def  Totalmark(marks):
  return sum(marks)
finalscore = Totalmark([10,20,30,40,50])
if finalscore>50:
  print("pass")


pass


Object Oriented Programming(OOP)



1.   class - blueprint, attributes- variables in class(feature of class), methods- function used inside class.
2.  encapsulation- functions inside class cannot be called
3. object/instance-





inheritance
polymorphism

abstraction

In [ ]:
class Animal:
  animal_type="dog"
  num_legs=4
  mammal="Yes"
  def sound(self):#self- is pointer to identify the instance
    print("bark")
obj1=Animal()#instance
print(obj1.animal_type)
obj1.sound()



dog
bark


In [ ]:
class person:
  place="tvm"

  def __init__(self,name,age):#constructor
    self.name=name
    self.age=age
  def greet(self):
    return f"Hi, myself {self.name} and my age is {self.age} i am from {self.place}"
obj1=person('Merin',23)
print(obj1.greet())
obj2=person('Maria',19)
print(obj2.greet())

Hi, myself Merin and my age is 23 i am from tvm
Hi, myself Maria and my age is 19 i am from tvm


In [ ]:
class Employee:
  def __init__(self, name, emp_id,salary):
    self.name=name
    self.emp_id=emp_id
    self.salary=salary
  def display_info(self):
    print(f"Name: {self.name}")
    print(f"Employee ID: {self.emp_id}")
    print(f"Salary:{self.salary}")
class Manager(Employee):
  def __init__(self, name, emp_id,salary, dept, teamSize, ):
    super().__init__(name, emp_id,salary)
    self.dept=dept
    self.teamSize=teamSize
  def display_manager_info(self):
    self.display_info()
    print(f"Department: {self.dept}")
    print(f"TeamSize: {self.teamSize}")
class Teamleader(Manager):
  def __init__(self, name, emp_id,salary, dept, teamSize, experience):
    super().__init__(name, emp_id,salary, dept, teamSize)
    self.experience=experience
  def display_leader_info(self):
    self.display_manager_info()
    print(f"Experience: {self.experience}")

obj1=Employee('Merin',1234,1000000)
obj1.display_info()

man1=Manager('Merin', 1234, 1000000, 'Mathematics', 5)
man1.display_manager_info()

te1=Teamleader('Merin', 1234, 1000000, 'Mathematics', 5, 4)
te1.display_leader_info()

Name: Merin
Employee ID: 1234
Salary:1000000
Name: Merin
Employee ID: 1234
Salary:1000000
Department: Mathematics
TeamSize: 5
Name: Merin
Employee ID: 1234
Salary:1000000
Department: Mathematics
TeamSize: 5
Experience: 4


In [ ]:
l=[5,8,2,7,3,8,10,10]
l.sort()
print(l)

[2, 3, 5, 7, 8, 8, 10, 10]


In [ ]:
a=0
for i in range (len(l)):
  a=a+l[i]
mean=a/len(l)
print(mean)

7.0


In [ ]:
if len(l)%2==0:
  med=(l[(len(l)//2)-1]+l[(len(l)//2)])/2
else:
  med=l[len(l)//2]
print(med)

8


In [ ]:
mod=3*med-2*mean
print(mod)

10.0


In [ ]:
l=[78, 85, 95, 50, 88, 45, 82, 91, 75, 60]
l.sort()
print(l)

[45, 50, 60, 75, 78, 82, 85, 88, 91, 95]


In [ ]:
a=0
for i in range (len(l)):
  a=a+l[i]
mean=a/len(l)
print(mean)

74.9


In [ ]:
if len(l)%2==0:
  med=(l[(len(l)//2)-1]+l[(len(l)//2)])/2
else:
  med=l[len(l)//2]
print(med)

80.0


In [ ]:
w=0
for i in range(len(l)):
  v=(l[i]-mean)**2
  w=w+v
var=w/len(l)
print(var)

273.29


In [ ]:
std=e**(1/2)
print(std)

16.53148511174964


In [ ]:
l=[85, 60, 72, 55, 105, 315, 380, 290, 190, 130, 95, 70]
l.sort()
print(l)


[55, 60, 70, 72, 85, 95, 105, 130, 190, 290, 315, 380]


In [ ]:
Q1=l[(len(list1)*25//100)-1]
print(Q1)

70


In [ ]:
Q2=l[(len(list1)*50//100)-1]
print(Q2)

95


In [ ]:
Q3=l[(len(list1)*75//100)-1]
print(Q3)

190


In [ ]:
IQR=Q3-Q1
print(IQR)

120


In [ ]:
lower_whisker=Q1-IQR*1.5
print(lower_whisker)

-110.0


In [ ]:
upper_whisker=Q3+IQR*1.5
print(upper_whisker)

370.0


In [ ]:
for i in l:
  if int(upper_whisker)<i or lower_whisker>i:
    print(i)

380


In [ ]:
list1=[200, 220, 210, 300, 250, 400, 240, 260, 500, 230]
list2=[50, 55, 52, 80, 60, 100, 58, 65, 120, 54]
list1.sort()
list2.sort()
a=0
for i in list1:
  a=a+i
mean1=a/len(list1)
print(mean1)

281.0


In [ ]:
a=0
for i in list2:
  a=a+i
mean2=a/len(list2)
print(mean2)

69.4


In [ ]:
if len(list1)%2==0:
  med1=(list1[(len(list1)//2)-1]+list1[(len(list1)//2)])/2
else:
  med1=list1[len(list1)//2]
print(med1)

245.0


In [ ]:
if len(list2)%2==0:
  med2=(list2[(len(list2)//2)-1]+list2[(len(list2)//2)])/2
else:
  med2=list2[len(list2)//2]
print(med2)

59.0


In [ ]:
o=0
for i in range(len(list1)):
  p=(list1[i]-mean1)**2
  o=o+p
var1=o/len(list1)
print(var1)

8349.0


In [ ]:
o=0
for i in range(len(list2)):
  p=(list2[i]-mean2)**2
  o=o+p
var2=o/len(list2)
print(var2)

497.03999999999996


In [ ]:
std1=var1**(1/2)
print(std1)
std2=var2**(1/2)
print(std2)

91.37286249209882
22.294393914165955


In [ ]:
o=0
for i,j in range (len(list1), len(list2)):
  p=(list1[i]-mean1)*(list2[j]-mean2)
  o=o+p
cov=o/len(list1)
print(cov)

0.0


In [ ]:
coorelation=cov/std1*std2
print(coorelation)

0.0


In [ ]:
## Q2. Write function that returns mean value of a list of numbers
def mean(l):
  a = 0
  for i in range(len(l)):
    a = a + l[i]

  return a/len(l)

In [ ]:
##Q8. Write a function to return standard deviation of a list of numbers
def standard_deviation(l):

  w = 0
  a = 0
  mean1 = mean(l)

  for i in range(len(l)):

    v = (l[i]-mean1)**2
    w = w + v
    variance = w/(len(l)-1)
    standard_dev = variance**(1/2)

  return standard_dev

In [ ]:
a1=mean([50,81,61,63,83,64,75,43])
b1=mean([48,50,39,53,60,47,60,85,52,52,63,49])

In [ ]:
a=standard_deviation([50,81,61,63,83,64,75,43])
print(a)

14.19255337945119


In [ ]:
b=standard_deviation([48,50,39,53,60,47,60,85,52,52,63,49])
print(b)

11.543068233464801


In [ ]:
Sp=((7*a**2+11*b**2)/18)**1/2
print(Sp)

79.87962962962962


In [ ]:
t=(a1-b1)/(Sp*((1/8)+(1/12)))

In [ ]:
print(t)

0.6109192071403733


#Library NumPy

In [ ]:
import numpy as np
x = np.array([1,2,3])
print(x)
type(x)

[1 2 3]


numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.dtype #datatype of numbers inside array

dtype('int64')

In [ ]:
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
y.shape

(3, 3)

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y.size # Number of elements in the array

9

In [ ]:
z=np.array([1.3,2.4,3.5,4.6], dtype=int)
print(z)

[1 2 3 4]


In [ ]:
z+3

array([4, 5, 6, 7])

In [ ]:
z-3

array([-2, -1,  0,  1])

In [ ]:
z*3

array([ 3,  6,  9, 12])

In [ ]:
z/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(1,20,2)

In [ ]:
len(a)

10

In [ ]:
a.shape

(10,)

In [ ]:
a.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [ ]:
import numpy as np
np.random.random((4,3))

array([[0.71963627, 0.60233419, 0.59097167],
       [0.35354223, 0.86490788, 0.14398679],
       [0.41392434, 0.74715663, 0.63414374],
       [0.39335703, 0.72728679, 0.29980731]])

In [ ]:
w=np.random.randint(3,10, size=(3,5)) # give values between 3 and 10
w

array([[8, 8, 4, 9, 9],
       [6, 9, 8, 5, 9],
       [6, 8, 3, 4, 6]])

In [ ]:
w[0]

array([8, 8, 4, 9, 9])

In [ ]:
w[1]

array([6, 9, 8, 5, 9])

In [ ]:
w[0,0]

np.int64(8)

In [ ]:
w[-1,-1]

np.int64(6)

In [ ]:
w[0:2,  0:2]

array([[8, 8, 4, 9, 9],
       [6, 9, 8, 5, 9]])

In [ ]:
w[-2:, -2:]

array([[5, 9],
       [4, 6]])

In [ ]:
e=np.array([1,2,3])
f=np.array([4,5,6])
np.concatenate((e,f))

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) #axis=1 → stack horizontally

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)   #axis=0 → stack vertically

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr = np.array([0, 0, 3, 0])

print(np.any(arr))     # True (because 3 is nonzero)
print(np.any(arr == 3)) # True (3 is present)
print(np.any(arr > 5))

True
True
False


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 4, 4], [1, 2, 3, 4, 5, 4, 4]])

x = np.where(arr == 4)

print(x)

(array([0, 0, 0, 1, 1, 1]), array([3, 5, 6, 3, 5, 6]))


In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='left')  #It finds the index where a given value should be inserted in a sorted array to maintain the sorting order.

print(x)

1


In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


#Pandas Library

In [ ]:
import pandas as pd
pd.Series([1,2,3,4,np.nan,6,7])

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
dtype: float64

In [ ]:
pd.DataFrame(np.random.randint(0,100,size=(5,3)), columns=['a', 's', 'd'])

a   s   d
0  66  48  11
1  32  16   2
2   3  81  85
3  67  17   9
4  68   5  26

In [ ]:
data={'Calaries':[20,30,40,50],
      'duration':[10,20,30,40]}
df=pd.DataFrame(data, index=['day1','day2','day3','day4'])

In [ ]:
df['Calaries']

day1    20
day2    30
day3    40
day4    50
Name: Calaries, dtype: int64

In [ ]:
df.loc['day1':'day3'] #row name

Calaries  duration
day1        20        10
day2        30        20
day3        40        30

In [ ]:
df.iloc[0:3]   #row index

Calaries  duration
day1        20        10
day2        30        20
day3        40        30

In [ ]:
df.reset_index(drop=True)

Calaries  duration
0        20        10
1        30        20
2        40        30
3        50        40

In [ ]:
url='https://docs.google.com/spreadsheets/d/1VdgNwORHh4HlimuuEgrsixRgko2Gi1YdnlUYAnkPFR8/export?format=csv&gid=0'
df=pd.read_csv(url)

In [ ]:
df=pd.read_csv('/content/data - Sheet1.csv')

In [ ]:
df.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df.shape

(169, 4)

In [ ]:
df.size

676

In [ ]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
df.describe() #numerical column statistical info

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
df.isna() #check whether the valus is na or not

Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
..        ...    ...       ...       ...
164     False  False     False     False
165     False  False     False     False
166     False  False     False     False
167     False  False     False     False
168     False  False     False     False

[169 rows x 4 columns]

In [ ]:
df.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
df[df['Calories']<=100]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
93         15     80       100      50.5
100        20     95       112      77.7
104        30     92       108      92.7
107        30     90       120      86.2

In [ ]:
df[(df['Calories']<=100) & (df['Duration']==20)]

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
100        20     95       112      77.7

In [ ]:
df.drop(columns=['Pulse'])

Duration  Maxpulse  Calories
0          60       130     409.1
1          60       145     479.0
2          60       135     340.0
3          45       175     282.4
4          45       148     406.0
..        ...       ...       ...
164        60       140     290.8
165        60       145     300.0
166        60       145     310.2
167        75       150     320.4
168        75       150     330.4

[169 rows x 3 columns]

In [ ]:
df.nunique()

Duration     16
Pulse        47
Maxpulse     57
Calories    142
dtype: int64

In [ ]:
df['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [ ]:
df['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
75      2
160     2
210     2
15      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [ ]:
df.groupby('Duration')['Calories'].mean()

Duration
15       87.350000
20      151.600000
25      244.200000
30      192.125000
45      273.236364
60      339.675000
75      325.400000
80      643.100000
90      541.800000
120     666.833333
150     939.400000
160     943.700000
180     733.600000
210    1618.200000
270    1729.000000
300    1500.200000
Name: Calories, dtype: float64

In [ ]:
df['calories_per_min']=df['Calories']/df['Duration']
print(df)

     Duration  Pulse  Maxpulse  Calories  calories_per_min
0          60    110       130     409.1          6.818333
1          60    117       145     479.0          7.983333
2          60    103       135     340.0          5.666667
3          45    109       175     282.4          6.275556
4          45    117       148     406.0          9.022222
..        ...    ...       ...       ...               ...
164        60    105       140     290.8          4.846667
165        60    110       145     300.0          5.000000
166        60    115       145     310.2          5.170000
167        75    120       150     320.4          4.272000
168        75    125       150     330.4          4.405333

[169 rows x 5 columns]


In [ ]:
import seaborn as sns
data = sns.load_dataset('titanic')

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
data.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [ ]:
data.shape

(891, 15)

In [ ]:
data.size

13365

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
data.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
data.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
data['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
data['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [ ]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
data.groupby('class')['survived'].mean()

/tmp/ipython-input-3832792271.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby('class')['survived'].mean()


class
First     0.629630
Second    0.472826
Third     0.242363
Name: survived, dtype: float64

In [ ]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64