<a href="https://colab.research.google.com/github/merinrose4007/DSA-class-activity/blob/main/Numpy_Pandas_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [2]:
# Create a NumPy array with values from 10 to 49 (inclusive).
#● Reshape it into a 4x10 matrix.
#● Then extract the last column from the reshaped matrix

import numpy as np

arr1=np.random.randint(10,50, size=(40))
print(arr1)
arr1=arr1.reshape(4,10)
print("Matrix of 4*10:\n",arr1)
print("last column:\n",arr1[0:,-1])

[23 24 10 21 35 41 29 40 47 30 29 17 18 43 14 39 13 21 10 22 33 27 19 36
 36 10 24 26 28 19 27 23 28 27 41 40 35 43 35 43]
Matrix of 4*10:
 [[23 24 10 21 35 41 29 40 47 30]
 [29 17 18 43 14 39 13 21 10 22]
 [33 27 19 36 36 10 24 26 28 19]
 [27 23 28 27 41 40 35 43 35 43]]
last column:
 [30 22 19 43]


In [3]:
#2. Create two 3×3 matrices:
#One filled with all 5s , One with values from 1 to 9
#● Add the two matrices
#● Multiply them element-wise
#● Then find the transpose of the result

A = np.full((3, 3), 5)
B = np.random.randint(1,10, size=(3,3))
print(A)
print(B)
C=np.add(A,B)
print(C)
D=np.multiply(A,B)
print(np.transpose(C))
print(np.transpose(D))

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[7 5 1]
 [4 4 3]
 [7 2 9]]
[[12 10  6]
 [ 9  9  8]
 [12  7 14]]
[[12  9 12]
 [10  9  7]
 [ 6  8 14]]
[[35 20 35]
 [25 20 10]
 [ 5 15 45]]


In [4]:
#3. Create a NumPy array of 15 random integers between 10 and 100.
#● Replace all values greater than 50 with -1
#● Count how many values were replaced.

arr2=np.random.randint(10,101, size=(20))
print(arr2)
x=np.where(arr2>50)
print(x)
for i in x:
  arr2[i]=-1
print(arr2)

[29 93 19 87 62 93 22 30 43 57 75 93 25 46 91 25 95 25 18 46]
(array([ 1,  3,  4,  5,  9, 10, 11, 14, 16]),)
[29 -1 19 -1 -1 -1 22 30 43 -1 -1 -1 25 46 -1 25 -1 25 18 46]


In [5]:
#4. Generate a 5×4 array with random values between 0 and 1 (float).
#● Find the row with the maximum sum of values.
#● Normalize each row using the formula:

mat1=np.random.random(size=(5,4))
arr3=np.sum(mat1, axis=1)
print(mat1)
print(arr3)
print(np.max(arr3))
max1=mat1.max(axis=1, keepdims=True)  # axis=1 takes the row maximum and keepdims keeps the max of each matrix a matrix
min1=mat1.min(axis=1, keepdims=True)
normalised=(mat1-min1)/(max1-min1)
print(normalised)


[[0.29051048 0.80946174 0.91199406 0.31692192]
 [0.56514057 0.08892242 0.21533749 0.18559734]
 [0.88806366 0.54239859 0.96030922 0.66894484]
 [0.01933607 0.06059758 0.12367598 0.22304002]
 [0.56232079 0.48313736 0.21061244 0.54570994]]
[2.32888819 1.05499783 3.05971631 0.42664964 1.80178052]
3.0597163111403027
[[0.         0.83502006 1.         0.0424974 ]
 [1.         0.         0.26545623 0.20300553]
 [0.82712677 0.         1.         0.30280697]
 [0.         0.20255625 0.51221348 1.        ]
 [1.         0.77486053 0.         0.95277094]]


In [6]:
#5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#● Find all unique elements
#● Find the duplicates (elements that appear more than once)

arr4 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique, count=np.unique(arr4, return_counts=True)
print(count)
l=np.array([], dtype=np.int64)
for i in range(len(count)):
  if count[i]>1:
    l=np.append(l,unique[i])
print(l)



[2 2 3 1 1]
[1 3 5]


In [7]:
#6. Create a 6×6 NumPy array with values from 1 to 36.
#● Extract the middle 4×4 submatrix.
#● Then extract all even numbers from this submatrix.

mat2 = np.random.randint(1,37, size=(6,6))
print(mat2)
mat2_sub=mat2[1:5,1:5]
print(mat2_sub)
even_nums = mat2_sub[mat2_sub % 2 == 0]
print(even_nums)

[[21 16 14 27 31 21]
 [28 14 36  5 17  5]
 [35 15 16 24 29 12]
 [31 19 36 26  1 36]
 [ 7 15 15 18 34 35]
 [14 24  5 33 26 25]]
[[14 36  5 17]
 [15 16 24 29]
 [19 36 26  1]
 [15 15 18 34]]
[14 36 16 24 36 26 18 34]


In [8]:
#7. Generate an array of shape (3, 4) with values from 0 to 11.
#● Reshape it to (2, 6)
#● Then flatten it into a 1D array
#● Convert the 1D array back to shape (4, 3)

mat3 = np.random.randint(1,12, size=(3,4))
mat4 = mat3.reshape(2,6)
print(mat3)
print(mat4)
mat5 = mat4.reshape(12)
print(mat5)
mat6=mat5.reshape(4,3)
print(mat6)

[[10  7 11 10]
 [ 1  8 11  1]
 [ 5  5  7  4]]
[[10  7 11 10  1  8]
 [11  1  5  5  7  4]]
[10  7 11 10  1  8 11  1  5  5  7  4]
[[10  7 11]
 [10  1  8]
 [11  1  5]
 [ 5  7  4]]


In [9]:
#8 . Create an array: a = np.array([[1, 2], [3, 4]])
#● Append a new row [5, 6]
#● Then append a new column [7, 8, 9]

mat7 = np.array([[1, 2], [3, 4]])
mat7 = np.append(mat7, [[5, 6]], axis=0)
print(mat7)
mat8 = np.append(mat7, [[7], [8], [9]], axis=1)
print(mat8)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [10]:
#9.a = np.array([1, 2, 3])
#b = np.array([4, 5, 6])
#c = np.array([7, 8, 9])
#● Join them into a single array
#● Reshape the result into a 3×3 matrix
#● Extract the diagonal elements

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

arr5=np.concatenate((a,b,c))
print(arr5)
mat9=arr5.reshape(3,3)
print(mat9)
diag_elements = np.diag(mat9)
print(diag_elements)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [11]:
#10. Create a NumPy array of integers from 1 to 20.
#● Extract all values that are divisible by 3 or 5.
#● Count how many such values exist.

arr6 = np.random.randint(1,12, size=(20))
values = arr6[(arr6 % 3 == 0) | (arr6 % 5 ==0)]  #we cannot use or in array
print(arr6)
print(values)
print(len(values))

[ 2  2  1  3  9  6  1  4  2  3  5  7  7  4  5 10 11  6  8 10]
[ 3  9  6  3  5  5 10  6 10]
9


#Pandas

In [12]:
#1. Load the Titanic dataset and display the first 10 rows.
import seaborn as sns
data = sns.load_dataset('titanic')
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [13]:
#2. Find the number of missing values in each column.
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [14]:
#3. Find the percentage of passengers who survived, grouped by gender.
data.groupby('sex')['survived'].mean()*100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [15]:
#4. Find the average, median, and standard deviation of passenger ages.

print(data['age'].mean())
print(data['age'].median())
print(data['age'].std())

29.69911764705882
28.0
14.526497332334044


In [17]:
#Count how many passengers were in each class (pclass).
data['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [19]:
#6. Show all passengers who were female, under age 18, and survived.
data[(data['sex']=='female') & (data['age']<18) & (data['alive']=='yes')]

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

In [20]:
#7. Replace missing age values with the median age.
data["age"].fillna(data["age"].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [22]:
#8. Create a column age_group with values:
#a. 'Child' for age < 18
#b. 'Adult' for age 18–60
#c. 'Senior' for age > 60
#d. Use: apply() or np.where() or custom function

def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

data['age_group'] = data['age'].apply(categorize_age)



In [23]:
#9. Display the top 5 passengers who paid the highest fare.
top5 = data.sort_values(by='fare', ascending=False).head(5)
print(top5)

     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior  


In [24]:
#10. Find the average fare paid, grouped by both pclass and sex.
data.groupby(['class', 'sex'])['fare'].mean()


/tmp/ipython-input-2627412132.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['class', 'sex'])['fare'].mean()


class   sex   
First   female    106.125798
        male       67.226127
Second  female     21.970121
        male       19.741782
Third   female     16.118810
        male       12.661633
Name: fare, dtype: float64

In [26]:
#11. Rename the following columns:
#a. 'sex' → 'gender'
#b. 'fare' → 'ticket_fare'

data.rename(columns={'sex': 'Gender', 'fare': 'Ticket_Fare'}, inplace=True)
print(data)

     survived  pclass  Gender   age  sibsp  parch  Ticket_Fare embarked  \
0           0       3    male  22.0      1      0       7.2500        S   
1           1       1  female  38.0      1      0      71.2833        C   
2           1       3  female  26.0      0      0       7.9250        S   
3           1       1  female  35.0      1      0      53.1000        S   
4           0       3    male  35.0      0      0       8.0500        S   
..        ...     ...     ...   ...    ...    ...          ...      ...   
886         0       2    male  27.0      0      0      13.0000        S   
887         1       1  female  19.0      0      0      30.0000        S   
888         0       3  female   NaN      1      2      23.4500        S   
889         1       1    male  26.0      0      0      30.0000        C   
890         0       3    male  32.0      0      0       7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone age_group  
0     Third    man       

In [29]:
#12. Count the number of passengers who survived and didn’t survive, grouped by class.

survival_counts = data.groupby(['class', 'alive']).size()
print(survival_counts)

class   alive
First   no        80
        yes      136
Second  no        97
        yes       87
Third   no       372
        yes      119
dtype: int64


/tmp/ipython-input-3876842863.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  survival_counts = data.groupby(['class', 'alive']).size()


In [31]:
#13. Find the average age of passengers grouped by both class and gender.

data.groupby(['class', 'Gender'])['age'].mean()

/tmp/ipython-input-812314647.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['class', 'Gender'])['age'].mean()


class   Gender
First   female    34.611765
        male      41.281386
Second  female    28.722973
        male      30.740707
Third   female    21.750000
        male      26.507589
Name: age, dtype: float64